name: Workflow para ejecutar Release


on:
  workflow_dispatch:
    branches:
      - develop
    inputs:
      ambiente:
        description: 'Ambiente en el que se desplegar치'     
        required: true
        default: 'dev'
      escaneoCodigo:
        description: 'Indica si se ejecuta el escaneo de c칩digo'     
        required: true
        default: 'NO'
      version:
        description: 'Versi칩n del c칩digo'     
        required: true
        default: '0.0.1'
       
        
jobs:
  execute-relese:
    name: Release
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Show info
      run: |
        echo "Hello ${{github.event.inputs.ambiente}}"
        echo "Hello ${{github.event.inputs.version}}"
    - name: jecuta Checkout
      uses: actions/checkout@v2