# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: deploy
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          repositories: '[{"id":"vmmh", "name":"GitHub wecoderg Apache Maven Packages", "url":"https://maven.pkg.github.com/vmmartinezh/*", "releases":{"enabled":"true"}, "snapshots":{"enabled":"true"}}]'
          servers: '[{ "id": "vmmh", "username": "vmmartinezh", "password": "${{ secrets.REPO_TOKEN }}" }]'
       
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s /home/runner/.m2/settings.xml
        env:
          GITHUB_TOKEN: ${{secrets.REPO_TOKEN }}